//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WorkPlanDataRawFKEntities : DbContext
    {
        public WorkPlanDataRawFKEntities()
            : base("name=WorkPlanDataRawFKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RPSettings> RPSettings { get; set; }
        public virtual DbSet<StockBalancesWithComments> StockBalancesWithComments { get; set; }
        public virtual DbSet<MesLocations> MesLocations { get; set; }
        public virtual DbSet<PlanOPZList> PlanOPZList { get; set; }
        public virtual DbSet<tApplication> tApplication { get; set; }
        public virtual DbSet<tColorSelection> tColorSelection { get; set; }
        public virtual DbSet<tMaterial> tMaterial { get; set; }
        public virtual DbSet<tMercuryRecordSelected> tMercuryRecordSelected { get; set; }
        public virtual DbSet<tUserRecordSelected> tUserRecordSelected { get; set; }
        public virtual DbSet<tPlannedMeatContainers> tPlannedMeatContainers { get; set; }
        public virtual DbSet<tConsurptionData> tConsurptionData { get; set; }
        public virtual DbSet<tBlockedMaterial> tBlockedMaterial { get; set; }
        public virtual DbSet<tBlockedProduct> tBlockedProduct { get; set; }
        public virtual DbSet<SystemTable> SystemTable { get; set; }
        public virtual DbSet<tComponentException> tComponentException { get; set; }
        public virtual DbSet<tWorkPlan> tWorkPlan { get; set; }
        public virtual DbSet<tWorkPlanDates> tWorkPlanDates { get; set; }
        public virtual DbSet<tWorkPlanElement> tWorkPlanElement { get; set; }
        public virtual DbSet<tLines> tLines { get; set; }
        public virtual DbSet<NavPurchaseTable> NavPurchaseTable { get; set; }
        public virtual DbSet<StockBalances> StockBalances { get; set; }
        public virtual DbSet<StockBalancesMes> StockBalancesMes { get; set; }
        public virtual DbSet<StockBalancesPlant> StockBalancesPlant { get; set; }
        public virtual DbSet<MesAreas> MesAreas { get; set; }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_Get_ConsurmptionData")]
        public virtual IQueryable<fn_Get_ConsurmptionData_Result> fn_Get_ConsurmptionData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Get_ConsurmptionData_Result>("[WorkPlanDataRawFKEntities].[fn_Get_ConsurmptionData]()");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_RPSettings")]
        public virtual IQueryable<fn_select_RPSettings_Result> fn_select_RPSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RPSettings_Result>("[WorkPlanDataRawFKEntities].[fn_select_RPSettings]()");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_RPSettingsByCode")]
        public virtual IQueryable<fn_select_RPSettingsByCode_Result> fn_select_RPSettingsByCode(string prodCode)
        {
            var prodCodeParameter = prodCode != null ?
                new ObjectParameter("ProdCode", prodCode) :
                new ObjectParameter("ProdCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RPSettingsByCode_Result>("[WorkPlanDataRawFKEntities].[fn_select_RPSettingsByCode](@ProdCode)", prodCodeParameter);
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_CommentDataID")]
        public virtual IQueryable<fn_select_CommentDataID_Result> fn_select_CommentDataID(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CommentDataID_Result>("[WorkPlanDataRawFKEntities].[fn_select_CommentDataID](@Code)", codeParameter);
        }
    
        public virtual ObjectResult<SelectStockBalances1_Result> SelectStockBalances1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalances1_Result>("SelectStockBalances1");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_PlannedMainData")]
        public virtual IQueryable<fn_select_PlannedMainData_Result> fn_select_PlannedMainData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_PlannedMainData_Result>("[WorkPlanDataRawFKEntities].[fn_select_PlannedMainData]()");
        }
    
        public virtual ObjectResult<pr_GetAlarmWaste_Result> pr_GetAlarmWaste()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetAlarmWaste_Result>("pr_GetAlarmWaste");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_ProductionByCodeAndPeriod")]
        public virtual IQueryable<fn_select_ProductionByCodeAndPeriod_Result> fn_select_ProductionByCodeAndPeriod(string productCode, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ProductionByCodeAndPeriod_Result>("[WorkPlanDataRawFKEntities].[fn_select_ProductionByCodeAndPeriod](@ProductCode, @dateStart, @dateEnd)", productCodeParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual int Pr_DeleteMercuryRecord(string materialCode)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteMercuryRecord", materialCodeParameter);
        }
    
        public virtual int Pr_DeleteUserRecord(string materialCode)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteUserRecord", materialCodeParameter);
        }
    
        public virtual ObjectResult<pr_GetOPZ_Result> pr_GetOPZ(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetOPZ_Result>("pr_GetOPZ", startParameter, endParameter);
        }
    
        public virtual int Pr_InsertUserRecord(string materialCode, string userName)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserRecord", materialCodeParameter, userNameParameter);
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_LaterStorageNames")]
        public virtual IQueryable<fn_select_LaterStorageNames_Result> fn_select_LaterStorageNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_LaterStorageNames_Result>("[WorkPlanDataRawFKEntities].[fn_select_LaterStorageNames]()");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_LatinStorageNames")]
        public virtual IQueryable<fn_select_LatinStorageNames_Result> fn_select_LatinStorageNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_LatinStorageNames_Result>("[WorkPlanDataRawFKEntities].[fn_select_LatinStorageNames]()");
        }
    
        public virtual int Pr_InsertMercuryRecord(string materialCode, string userName)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertMercuryRecord", materialCodeParameter, userNameParameter);
        }
    
        public virtual int Insert_WorkPlanTableRecord1(Nullable<System.DateTime> datework, string lineName, string prodCode, string group, Nullable<double> quantity)
        {
            var dateworkParameter = datework.HasValue ?
                new ObjectParameter("datework", datework) :
                new ObjectParameter("datework", typeof(System.DateTime));
    
            var lineNameParameter = lineName != null ?
                new ObjectParameter("LineName", lineName) :
                new ObjectParameter("LineName", typeof(string));
    
            var prodCodeParameter = prodCode != null ?
                new ObjectParameter("ProdCode", prodCode) :
                new ObjectParameter("ProdCode", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("Group", group) :
                new ObjectParameter("Group", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_WorkPlanTableRecord1", dateworkParameter, lineNameParameter, prodCodeParameter, groupParameter, quantityParameter);
        }
    
        public virtual int Update_WorkPlanTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_WorkPlanTable");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_CommentData")]
        public virtual IQueryable<fn_select_CommentData_Result> fn_select_CommentData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CommentData_Result>("[WorkPlanDataRawFKEntities].[fn_select_CommentData]()");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_StockBalancesWithComments")]
        public virtual IQueryable<fn_select_StockBalancesWithComments_Result> fn_select_StockBalancesWithComments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_StockBalancesWithComments_Result>("[WorkPlanDataRawFKEntities].[fn_select_StockBalancesWithComments]()");
        }
    
        public virtual int pr_InsertCommentData1(Nullable<long> iD, string code, string naim, Nullable<bool> active, string comment, string userName)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var naimParameter = naim != null ?
                new ObjectParameter("Naim", naim) :
                new ObjectParameter("Naim", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertCommentData1", iDParameter, codeParameter, naimParameter, activeParameter, commentParameter, userNameParameter);
        }
    
        public virtual int Pr_UpdateMesArea(Nullable<long> iD, Nullable<bool> fl)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var flParameter = fl.HasValue ?
                new ObjectParameter("fl", fl) :
                new ObjectParameter("fl", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateMesArea", iDParameter, flParameter);
        }
    
        public virtual int Pr_UpdateMesLocation(Nullable<long> iD, Nullable<bool> fl)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var flParameter = fl.HasValue ?
                new ObjectParameter("fl", fl) :
                new ObjectParameter("fl", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateMesLocation", iDParameter, flParameter);
        }
    
        public virtual int Pr_InsertUserAppData1(Nullable<System.DateTime> dateWork, Nullable<System.DateTime> alterWork, string materialCode, Nullable<double> quantity)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var alterWorkParameter = alterWork.HasValue ?
                new ObjectParameter("AlterWork", alterWork) :
                new ObjectParameter("AlterWork", typeof(System.DateTime));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserAppData1", dateWorkParameter, alterWorkParameter, materialCodeParameter, quantityParameter);
        }
    
        public virtual int Pr_DeleteAppRecord(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteAppRecord", iDParameter);
        }
    
        public virtual int pr_DeleteTestData(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_DeleteTestData", iDParameter);
        }
    
        public virtual int pr_InsertTestData1(Nullable<long> iD, string code, string name, Nullable<bool> res)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var resParameter = res.HasValue ?
                new ObjectParameter("Res", res) :
                new ObjectParameter("Res", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertTestData1", iDParameter, codeParameter, nameParameter, resParameter);
        }
    
        public virtual int Pr_InsertUserCompData(Nullable<long> id, string compName, string objectCode, string cFOCode, string cFOSolut, string address)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var compNameParameter = compName != null ?
                new ObjectParameter("CompName", compName) :
                new ObjectParameter("CompName", typeof(string));
    
            var objectCodeParameter = objectCode != null ?
                new ObjectParameter("ObjectCode", objectCode) :
                new ObjectParameter("ObjectCode", typeof(string));
    
            var cFOCodeParameter = cFOCode != null ?
                new ObjectParameter("CFOCode", cFOCode) :
                new ObjectParameter("CFOCode", typeof(string));
    
            var cFOSolutParameter = cFOSolut != null ?
                new ObjectParameter("CFOSolut", cFOSolut) :
                new ObjectParameter("CFOSolut", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserCompData", idParameter, compNameParameter, objectCodeParameter, cFOCodeParameter, cFOSolutParameter, addressParameter);
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_RecipesBisView")]
        public virtual IQueryable<fn_select_RecipesBisView_Result> fn_select_RecipesBisView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesBisView_Result>("[WorkPlanDataRawFKEntities].[fn_select_RecipesBisView]()");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_RecipesView")]
        public virtual IQueryable<fn_select_RecipesView_Result> fn_select_RecipesView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesView_Result>("[WorkPlanDataRawFKEntities].[fn_select_RecipesView]()");
        }
    
        public virtual ObjectResult<SelectStockBalancesMes1_Result> SelectStockBalancesMes1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesMes1_Result>("SelectStockBalancesMes1");
        }
    
        public virtual ObjectResult<SelectStockBalancesPlant2_Result> SelectStockBalancesPlant2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesPlant2_Result>("SelectStockBalancesPlant2");
        }
    
        [DbFunction("WorkPlanDataRawFKEntities", "fn_select_ProductionByCode")]
        public virtual IQueryable<fn_select_ProductionByCode_Result> fn_select_ProductionByCode(string productCode, Nullable<System.DateTime> dateStart)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ProductionByCode_Result>("[WorkPlanDataRawFKEntities].[fn_select_ProductionByCode](@ProductCode, @dateStart)", productCodeParameter, dateStartParameter);
        }
    }
}
