//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavPurchaseView
    {
        public System.DateTime WorkDate { get; set; }
        public string Executor { get; set; }
        public string OrderType { get; set; }
        public string Status { get; set; }
        public string NextStatus { get; set; }
        public Nullable<System.DateTime> NessDateOrder { get; set; }
        public string Comment { get; set; }
        public string OrderNymber { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string Comment1 { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> FromBalanses { get; set; }
        public string EdIzm { get; set; }
        public string CFO { get; set; }
        public string Initiator { get; set; }
        public int NumberRowMZZ { get; set; }
        public string MZP { get; set; }
        public string StatusMZP { get; set; }
        public int NumberRowMZP { get; set; }
        public string ContrAgent { get; set; }
        public string MZPCode { get; set; }
        public string MZPNaim { get; set; }
        public Nullable<decimal> MZPQuantity { get; set; }
        public string MZPEdIzm { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<System.DateTime> PlanOperDate { get; set; }
        public string ENSGroupCode { get; set; }
        public string ENSGroup { get; set; }
        public Nullable<decimal> PlanQuantity { get; set; }
        public Nullable<decimal> FactQuantity { get; set; }
        public string ContrAgentCode { get; set; }
        public Nullable<decimal> DayToSend { get; set; }
        public decimal CurrPrice { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> DateCreateMZP { get; set; }
        public string CFOCode { get; set; }
        public Nullable<int> CurrStatusCode { get; set; }
        public string CurrStatus { get; set; }
        public Nullable<int> NextStatusCode { get; set; }
        public Nullable<System.DateTime> LastStatusDate { get; set; }
        public Nullable<System.DateTime> LastStatusTime { get; set; }
        public Nullable<System.DateTime> DateCreateZZ { get; set; }
        public string Address { get; set; }
        public string QuantityKey { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
    }
}
