//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavPurchaseTable
    {
        public long id { get; set; }
        public System.DateTime DateWork { get; set; }
        public string Executor { get; set; }
        public string OrderType { get; set; }
        public string Status { get; set; }
        public string NextStatus { get; set; }
        public System.DateTime NessDateOrder { get; set; }
        public string Comment { get; set; }
        public string OrderNymber { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string Comment1 { get; set; }
        public double Quantity { get; set; }
        public double FromBalanses { get; set; }
        public string EdIzm { get; set; }
        public string CFO { get; set; }
        public string Initiator { get; set; }
        public long NumberRowMZZ { get; set; }
        public string MZP { get; set; }
        public string StatusMZP { get; set; }
        public long NumberRowMZP { get; set; }
        public string ContrAgent { get; set; }
        public string MZPCode { get; set; }
        public string MZPNaim { get; set; }
        public double MZPQuantity { get; set; }
        public string MZPEdIzm { get; set; }
        public System.DateTime PlanDate { get; set; }
        public System.DateTime PlanOperDate { get; set; }
        public string ENSGroupCode { get; set; }
        public string ENSGroup { get; set; }
        public double PlanQuantity { get; set; }
        public double FactQuantity { get; set; }
        public string ContrAgentCode { get; set; }
        public int DayToSend { get; set; }
        public double CurrPrice { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime DateCreateMZP { get; set; }
        public string CFOCode { get; set; }
        public string CurrStatusCode { get; set; }
        public string CurrStatus { get; set; }
        public string NextStatusCode { get; set; }
        public System.DateTime LastStatusDate { get; set; }
        public System.DateTime LastStatusTime { get; set; }
        public System.DateTime DateCreateZZ { get; set; }
        public string Address { get; set; }
        public string QuantityKey { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
    }
}
