//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalancesPlant
    {
        public long id { get; set; }
        public int StorageID { get; set; }
        public string Storage { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string MatGroup { get; set; }
        public string MatGroupName { get; set; }
        public string MatGroupAlter { get; set; }
        public string LotName { get; set; }
        public string LotDescription { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public string MaterialOwner { get; set; }
        public string TestQuality { get; set; }
        public string StorageType { get; set; }
        public string TestQualityGr { get; set; }
        public string TestOnStorage { get; set; }
        public System.DateTime ProdDate { get; set; }
        public System.DateTime BBFDate { get; set; }
        public int dpr { get; set; }
        public int bbf { get; set; }
        public int difdates { get; set; }
        public int difcurdates { get; set; }
        public string st { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string DayPeriod { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
    }
}
