//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTable
    {
        public long id { get; set; }
        public string CompName { get; set; }
        public string ObjectCode { get; set; }
        public string CFOCode { get; set; }
        public string CFOSolut { get; set; }
        public string Address { get; set; }
    }
}
