//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApplication
    {
        public long id { get; set; }
        public System.DateTime DateWork { get; set; }
        public string MaterialCode { get; set; }
        public double Quantity { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
    }
}
