//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMaterial
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public int MaterialGroupID { get; set; }
        public string MaterialCode { get; set; }
        public string Units { get; set; }
        public double PlannedSize { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
        public Nullable<int> deliveryfrequency { get; set; }
        public Nullable<int> delivmindays { get; set; }
        public Nullable<int> insurancestock { get; set; }
        public string lastsender { get; set; }
    }
}
