//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMesPlantRelations
    {
        public int ID { get; set; }
        public int MesID { get; set; }
        public int PlantID { get; set; }
        public bool IsActive { get; set; }
    }
}
