//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class IfProductionConsumptionPerformances
    {
        public long IfProductionConsumptionPerformanceID { get; set; }
        public int IfRecordActionID { get; set; }
        public int IfRecordStatus { get; set; }
        public System.DateTime IfRecordDateLastProcessed { get; set; }
        public string IfRecordProcessedBy { get; set; }
        public string IfRecordComments { get; set; }
        public string ProductionResponseID { get; set; }
        public System.DateTime ProductionResponseDateCreated { get; set; }
        public string ProductionResponseCreatedBy { get; set; }
        public string MaterialID { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialLotID { get; set; }
        public double MaterialLotQuantity { get; set; }
        public string MaterialLotUOM { get; set; }
    }
}
