//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesLocations
    {
        public int ID { get; set; }
        public int AreaID { get; set; }
        public string LocationName { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> MesLocationID { get; set; }
        public string MesLocationName { get; set; }
        public string LocationType { get; set; }
        public string MesLocCyrName { get; set; }
    }
}
