//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestDataEntities : DbContext
    {
        public TestDataEntities()
            : base("name=TestDataEntities")
        {
            this.Database.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NavPurchaseTable> NavPurchaseTable { get; set; }
        public virtual DbSet<SystemTable> SystemTable { get; set; }
        public virtual DbSet<tApplication> tApplication { get; set; }
        public virtual DbSet<tColorSelection> tColorSelection { get; set; }
        public virtual DbSet<tExcelData> tExcelData { get; set; }
        public virtual DbSet<tPlannedMeatContainers> tPlannedMeatContainers { get; set; }
        public virtual DbSet<tUserRecordSelected> tUserRecordSelected { get; set; }
        public virtual DbSet<tWorkPlan> tWorkPlan { get; set; }
        public virtual DbSet<tWorkPlanDates> tWorkPlanDates { get; set; }
        public virtual DbSet<tWorkPlanElement> tWorkPlanElement { get; set; }
        public virtual DbSet<tMappingTable> tMappingTable { get; set; }
        public virtual DbSet<StockBalancesWithComments> StockBalancesWithComments { get; set; }
        public virtual DbSet<tBlockedProduct> tBlockedProduct { get; set; }
        public virtual DbSet<tBlockedMaterial> tBlockedMaterial { get; set; }
        public virtual DbSet<PlanOPZList> PlanOPZList { get; set; }
        public virtual DbSet<tComponentException> tComponentException { get; set; }
        public virtual DbSet<tMercuryRecordSelected> tMercuryRecordSelected { get; set; }
        public virtual DbSet<tConsurptionData> tConsurptionData { get; set; }
        public virtual DbSet<MesAreas> MesAreas { get; set; }
        public virtual DbSet<MesLocations> MesLocations { get; set; }
    
        [DbFunction("TestDataEntities", "fn_select_CurrentComponents")]
        public virtual IQueryable<fn_select_CurrentComponents_Result> fn_select_CurrentComponents(Nullable<System.DateTime> dateWork, Nullable<double> vGP, string productCode)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var vGPParameter = vGP.HasValue ?
                new ObjectParameter("VGP", vGP) :
                new ObjectParameter("VGP", typeof(double));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentComponents_Result>("[TestDataEntities].[fn_select_CurrentComponents](@DateWork, @VGP, @ProductCode)", dateWorkParameter, vGPParameter, productCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_CurrentProduct")]
        public virtual IQueryable<fn_select_CurrentProduct_Result> fn_select_CurrentProduct(Nullable<System.DateTime> dateWork, string productCode)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentProduct_Result>("[TestDataEntities].[fn_select_CurrentProduct](@DateWork, @ProductCode)", dateWorkParameter, productCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_CurrentProduct1")]
        public virtual IQueryable<fn_select_CurrentProduct1_Result> fn_select_CurrentProduct1(Nullable<System.DateTime> dateWork, string productCode)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentProduct1_Result>("[TestDataEntities].[fn_select_CurrentProduct1](@DateWork, @ProductCode)", dateWorkParameter, productCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_ExcelData")]
        public virtual IQueryable<fn_select_ExcelData_Result> fn_select_ExcelData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ExcelData_Result>("[TestDataEntities].[fn_select_ExcelData]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_ExcelData1")]
        public virtual IQueryable<fn_select_ExcelData1_Result> fn_select_ExcelData1(Nullable<System.DateTime> dt)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ExcelData1_Result>("[TestDataEntities].[fn_select_ExcelData1](@dt)", dtParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_ExcelDataByCodeAndDate")]
        public virtual IQueryable<fn_select_ExcelDataByCodeAndDate_Result> fn_select_ExcelDataByCodeAndDate(string lineName, string productCode, Nullable<System.DateTime> dateWork)
        {
            var lineNameParameter = lineName != null ?
                new ObjectParameter("LineName", lineName) :
                new ObjectParameter("LineName", typeof(string));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ExcelDataByCodeAndDate_Result>("[TestDataEntities].[fn_select_ExcelDataByCodeAndDate](@LineName, @ProductCode, @DateWork)", lineNameParameter, productCodeParameter, dateWorkParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_PlannedMainData")]
        public virtual IQueryable<fn_select_PlannedMainData_Result> fn_select_PlannedMainData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_PlannedMainData_Result>("[TestDataEntities].[fn_select_PlannedMainData]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_RecipeByCode")]
        public virtual IQueryable<fn_select_RecipeByCode_Result> fn_select_RecipeByCode(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipeByCode_Result>("[TestDataEntities].[fn_select_RecipeByCode](@ProductCode)", productCodeParameter);
        }
    
        public virtual int InsertExcelData(Nullable<long> iD, string lineName, Nullable<System.DateTime> dateWork, string productCode, Nullable<double> productQuantity)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var lineNameParameter = lineName != null ?
                new ObjectParameter("LineName", lineName) :
                new ObjectParameter("LineName", typeof(string));
    
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var productQuantityParameter = productQuantity.HasValue ?
                new ObjectParameter("ProductQuantity", productQuantity) :
                new ObjectParameter("ProductQuantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertExcelData", iDParameter, lineNameParameter, dateWorkParameter, productCodeParameter, productQuantityParameter);
        }
    
        public virtual int InsertPlannedMeatContainers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPlannedMeatContainers");
        }
    
        public virtual int InsertPurchaseNavTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPurchaseNavTask");
        }
    
        public virtual int InsertStockBalanse(string storage, string materialCode, string materialName, string matGroup, string lotName, string lotDescription, Nullable<decimal> quantity, string materialOwner, string testQuality, string storageType, string testQualityGt, string testOnStorage, Nullable<System.DateTime> prodDate, Nullable<System.DateTime> bBFDate, Nullable<int> dpr, Nullable<int> bbf, Nullable<int> difdates, Nullable<int> difcurdates, string st)
        {
            var storageParameter = storage != null ?
                new ObjectParameter("Storage", storage) :
                new ObjectParameter("Storage", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var matGroupParameter = matGroup != null ?
                new ObjectParameter("MatGroup", matGroup) :
                new ObjectParameter("MatGroup", typeof(string));
    
            var lotNameParameter = lotName != null ?
                new ObjectParameter("LotName", lotName) :
                new ObjectParameter("LotName", typeof(string));
    
            var lotDescriptionParameter = lotDescription != null ?
                new ObjectParameter("LotDescription", lotDescription) :
                new ObjectParameter("LotDescription", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(decimal));
    
            var materialOwnerParameter = materialOwner != null ?
                new ObjectParameter("MaterialOwner", materialOwner) :
                new ObjectParameter("MaterialOwner", typeof(string));
    
            var testQualityParameter = testQuality != null ?
                new ObjectParameter("TestQuality", testQuality) :
                new ObjectParameter("TestQuality", typeof(string));
    
            var storageTypeParameter = storageType != null ?
                new ObjectParameter("StorageType", storageType) :
                new ObjectParameter("StorageType", typeof(string));
    
            var testQualityGtParameter = testQualityGt != null ?
                new ObjectParameter("TestQualityGt", testQualityGt) :
                new ObjectParameter("TestQualityGt", typeof(string));
    
            var testOnStorageParameter = testOnStorage != null ?
                new ObjectParameter("TestOnStorage", testOnStorage) :
                new ObjectParameter("TestOnStorage", typeof(string));
    
            var prodDateParameter = prodDate.HasValue ?
                new ObjectParameter("ProdDate", prodDate) :
                new ObjectParameter("ProdDate", typeof(System.DateTime));
    
            var bBFDateParameter = bBFDate.HasValue ?
                new ObjectParameter("BBFDate", bBFDate) :
                new ObjectParameter("BBFDate", typeof(System.DateTime));
    
            var dprParameter = dpr.HasValue ?
                new ObjectParameter("dpr", dpr) :
                new ObjectParameter("dpr", typeof(int));
    
            var bbfParameter = bbf.HasValue ?
                new ObjectParameter("bbf", bbf) :
                new ObjectParameter("bbf", typeof(int));
    
            var difdatesParameter = difdates.HasValue ?
                new ObjectParameter("difdates", difdates) :
                new ObjectParameter("difdates", typeof(int));
    
            var difcurdatesParameter = difcurdates.HasValue ?
                new ObjectParameter("difcurdates", difcurdates) :
                new ObjectParameter("difcurdates", typeof(int));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalanse", storageParameter, materialCodeParameter, materialNameParameter, matGroupParameter, lotNameParameter, lotDescriptionParameter, quantityParameter, materialOwnerParameter, testQualityParameter, storageTypeParameter, testQualityGtParameter, testOnStorageParameter, prodDateParameter, bBFDateParameter, dprParameter, bbfParameter, difdatesParameter, difcurdatesParameter, stParameter);
        }
    
        public virtual int InsertStockBalanse1(string storage, string materialCode, string materialName, string matGroup, string lotName, string lotDescription, Nullable<decimal> quantity, string materialOwner, string testQuality, string storageType, string testQualityGt, string testOnStorage, Nullable<System.DateTime> prodDate, Nullable<System.DateTime> bBFDate, Nullable<int> dpr, Nullable<int> bbf, Nullable<int> difdates, Nullable<int> difcurdates, string st, Nullable<bool> period)
        {
            var storageParameter = storage != null ?
                new ObjectParameter("Storage", storage) :
                new ObjectParameter("Storage", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var matGroupParameter = matGroup != null ?
                new ObjectParameter("MatGroup", matGroup) :
                new ObjectParameter("MatGroup", typeof(string));
    
            var lotNameParameter = lotName != null ?
                new ObjectParameter("LotName", lotName) :
                new ObjectParameter("LotName", typeof(string));
    
            var lotDescriptionParameter = lotDescription != null ?
                new ObjectParameter("LotDescription", lotDescription) :
                new ObjectParameter("LotDescription", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(decimal));
    
            var materialOwnerParameter = materialOwner != null ?
                new ObjectParameter("MaterialOwner", materialOwner) :
                new ObjectParameter("MaterialOwner", typeof(string));
    
            var testQualityParameter = testQuality != null ?
                new ObjectParameter("TestQuality", testQuality) :
                new ObjectParameter("TestQuality", typeof(string));
    
            var storageTypeParameter = storageType != null ?
                new ObjectParameter("StorageType", storageType) :
                new ObjectParameter("StorageType", typeof(string));
    
            var testQualityGtParameter = testQualityGt != null ?
                new ObjectParameter("TestQualityGt", testQualityGt) :
                new ObjectParameter("TestQualityGt", typeof(string));
    
            var testOnStorageParameter = testOnStorage != null ?
                new ObjectParameter("TestOnStorage", testOnStorage) :
                new ObjectParameter("TestOnStorage", typeof(string));
    
            var prodDateParameter = prodDate.HasValue ?
                new ObjectParameter("ProdDate", prodDate) :
                new ObjectParameter("ProdDate", typeof(System.DateTime));
    
            var bBFDateParameter = bBFDate.HasValue ?
                new ObjectParameter("BBFDate", bBFDate) :
                new ObjectParameter("BBFDate", typeof(System.DateTime));
    
            var dprParameter = dpr.HasValue ?
                new ObjectParameter("dpr", dpr) :
                new ObjectParameter("dpr", typeof(int));
    
            var bbfParameter = bbf.HasValue ?
                new ObjectParameter("bbf", bbf) :
                new ObjectParameter("bbf", typeof(int));
    
            var difdatesParameter = difdates.HasValue ?
                new ObjectParameter("difdates", difdates) :
                new ObjectParameter("difdates", typeof(int));
    
            var difcurdatesParameter = difcurdates.HasValue ?
                new ObjectParameter("difcurdates", difcurdates) :
                new ObjectParameter("difcurdates", typeof(int));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalanse1", storageParameter, materialCodeParameter, materialNameParameter, matGroupParameter, lotNameParameter, lotDescriptionParameter, quantityParameter, materialOwnerParameter, testQualityParameter, storageTypeParameter, testQualityGtParameter, testOnStorageParameter, prodDateParameter, bBFDateParameter, dprParameter, bbfParameter, difdatesParameter, difcurdatesParameter, stParameter, periodParameter);
        }
    
        public virtual int InsertStockBalanseMes(string storage, string materialCode, string materialName, string materialLot, Nullable<double> quantity, string owner, Nullable<bool> period)
        {
            var storageParameter = storage != null ?
                new ObjectParameter("Storage", storage) :
                new ObjectParameter("Storage", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var materialLotParameter = materialLot != null ?
                new ObjectParameter("MaterialLot", materialLot) :
                new ObjectParameter("MaterialLot", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var ownerParameter = owner != null ?
                new ObjectParameter("Owner", owner) :
                new ObjectParameter("Owner", typeof(string));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalanseMes", storageParameter, materialCodeParameter, materialNameParameter, materialLotParameter, quantityParameter, ownerParameter, periodParameter);
        }
    
        public virtual int InsertStockBalanseMesTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalanseMesTask");
        }
    
        public virtual int InsertStockBalansePlant(string materialCode, string materialName, string materialLotName, Nullable<System.DateTime> prodDate, Nullable<double> quantity, Nullable<bool> period)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var materialLotNameParameter = materialLotName != null ?
                new ObjectParameter("MaterialLotName", materialLotName) :
                new ObjectParameter("MaterialLotName", typeof(string));
    
            var prodDateParameter = prodDate.HasValue ?
                new ObjectParameter("ProdDate", prodDate) :
                new ObjectParameter("ProdDate", typeof(System.DateTime));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalansePlant", materialCodeParameter, materialNameParameter, materialLotNameParameter, prodDateParameter, quantityParameter, periodParameter);
        }
    
        public virtual int InsertStockBalansePlantBis(string materialCode, string materialName, string materialLotName, Nullable<System.DateTime> prodDate, Nullable<double> quantity, Nullable<bool> period, Nullable<int> workUnitID, Nullable<int> workUnitType)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var materialLotNameParameter = materialLotName != null ?
                new ObjectParameter("MaterialLotName", materialLotName) :
                new ObjectParameter("MaterialLotName", typeof(string));
    
            var prodDateParameter = prodDate.HasValue ?
                new ObjectParameter("ProdDate", prodDate) :
                new ObjectParameter("ProdDate", typeof(System.DateTime));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(bool));
    
            var workUnitIDParameter = workUnitID.HasValue ?
                new ObjectParameter("WorkUnitID", workUnitID) :
                new ObjectParameter("WorkUnitID", typeof(int));
    
            var workUnitTypeParameter = workUnitType.HasValue ?
                new ObjectParameter("WorkUnitType", workUnitType) :
                new ObjectParameter("WorkUnitType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalansePlantBis", materialCodeParameter, materialNameParameter, materialLotNameParameter, prodDateParameter, quantityParameter, periodParameter, workUnitIDParameter, workUnitTypeParameter);
        }
    
        public virtual int InsertStockBalansePlantTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalansePlantTask");
        }
    
        public virtual int InsertStockBalanseTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStockBalanseTask");
        }
    
        public virtual int Pr_DeleteUserRecord(string materialCode)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteUserRecord", materialCodeParameter);
        }
    
        public virtual int Pr_InsertUserAppData(Nullable<System.DateTime> dateWork, string materialCode, Nullable<double> quantity)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserAppData", dateWorkParameter, materialCodeParameter, quantityParameter);
        }
    
        public virtual int Pr_InsertUserCompData(Nullable<long> id, string compName, string objectCode, string cFOCode, string cFOSolut, string address)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var compNameParameter = compName != null ?
                new ObjectParameter("CompName", compName) :
                new ObjectParameter("CompName", typeof(string));
    
            var objectCodeParameter = objectCode != null ?
                new ObjectParameter("ObjectCode", objectCode) :
                new ObjectParameter("ObjectCode", typeof(string));
    
            var cFOCodeParameter = cFOCode != null ?
                new ObjectParameter("CFOCode", cFOCode) :
                new ObjectParameter("CFOCode", typeof(string));
    
            var cFOSolutParameter = cFOSolut != null ?
                new ObjectParameter("CFOSolut", cFOSolut) :
                new ObjectParameter("CFOSolut", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserCompData", idParameter, compNameParameter, objectCodeParameter, cFOCodeParameter, cFOSolutParameter, addressParameter);
        }
    
        public virtual int Pr_InsertUserRecord(string materialCode, string userName)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserRecord", materialCodeParameter, userNameParameter);
        }
    
        public virtual ObjectResult<SelectStockBalances_Result> SelectStockBalances()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalances_Result>("SelectStockBalances");
        }
    
        public virtual ObjectResult<SelectStockBalances1_Result> SelectStockBalances1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalances1_Result>("SelectStockBalances1");
        }
    
        public virtual ObjectResult<SelectStockBalancesPlant_Result> SelectStockBalancesPlant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesPlant_Result>("SelectStockBalancesPlant");
        }
    
        public virtual ObjectResult<SelectStockBalancesPlant1_Result> SelectStockBalancesPlant1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesPlant1_Result>("SelectStockBalancesPlant1");
        }
    
        public virtual int ClearExcelData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearExcelData");
        }
    
        public virtual int pr_DeleteTestData(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_DeleteTestData", iDParameter);
        }
    
        public virtual int pr_InsertTestData(Nullable<long> iD, string code, string name)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertTestData", iDParameter, codeParameter, nameParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_RecipesList")]
        public virtual IQueryable<fn_select_RecipesList_Result> fn_select_RecipesList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesList_Result>("[TestDataEntities].[fn_select_RecipesList]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_StockBalancesWithComments")]
        public virtual IQueryable<fn_select_StockBalancesWithComments_Result> fn_select_StockBalancesWithComments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_StockBalancesWithComments_Result>("[TestDataEntities].[fn_select_StockBalancesWithComments]()");
        }
    
        public virtual int Pr_UpdateMesArea(Nullable<long> iD, Nullable<bool> fl)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var flParameter = fl.HasValue ?
                new ObjectParameter("fl", fl) :
                new ObjectParameter("fl", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateMesArea", iDParameter, flParameter);
        }
    
        public virtual int Pr_UpdateMesLocation(Nullable<long> iD, Nullable<bool> fl)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var flParameter = fl.HasValue ?
                new ObjectParameter("fl", fl) :
                new ObjectParameter("fl", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_UpdateMesLocation", iDParameter, flParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_LaterStorageNames")]
        public virtual IQueryable<fn_select_LaterStorageNames_Result> fn_select_LaterStorageNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_LaterStorageNames_Result>("[TestDataEntities].[fn_select_LaterStorageNames]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_CurrentProductS")]
        public virtual IQueryable<fn_select_CurrentProductS_Result> fn_select_CurrentProductS(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentProductS_Result>("[TestDataEntities].[fn_select_CurrentProductS](@ProductCode)", productCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_ProductionByCode")]
        public virtual IQueryable<fn_select_ProductionByCode_Result> fn_select_ProductionByCode(string productCode, Nullable<System.DateTime> dateStart)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ProductionByCode_Result>("[TestDataEntities].[fn_select_ProductionByCode](@ProductCode, @dateStart)", productCodeParameter, dateStartParameter);
        }
    
        public virtual int Pr_InsertUserAppData1(Nullable<System.DateTime> dateWork, Nullable<System.DateTime> alterWork, string materialCode, Nullable<double> quantity)
        {
            var dateWorkParameter = dateWork.HasValue ?
                new ObjectParameter("DateWork", dateWork) :
                new ObjectParameter("DateWork", typeof(System.DateTime));
    
            var alterWorkParameter = alterWork.HasValue ?
                new ObjectParameter("AlterWork", alterWork) :
                new ObjectParameter("AlterWork", typeof(System.DateTime));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertUserAppData1", dateWorkParameter, alterWorkParameter, materialCodeParameter, quantityParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_RecipesBis")]
        public virtual IQueryable<fn_select_RecipesBis_Result> fn_select_RecipesBis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesBis_Result>("[TestDataEntities].[fn_select_RecipesBis]()");
        }
    
        public virtual int pr_InsertTestData1(Nullable<long> iD, string code, string name, Nullable<bool> res)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var resParameter = res.HasValue ?
                new ObjectParameter("Res", res) :
                new ObjectParameter("Res", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertTestData1", iDParameter, codeParameter, nameParameter, resParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_BasicRecipes")]
        public virtual IQueryable<fn_select_BasicRecipes_Result> fn_select_BasicRecipes(string prodCode)
        {
            var prodCodeParameter = prodCode != null ?
                new ObjectParameter("ProdCode", prodCode) :
                new ObjectParameter("ProdCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_BasicRecipes_Result>("[TestDataEntities].[fn_select_BasicRecipes](@ProdCode)", prodCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_Recipes")]
        public virtual IQueryable<fn_select_Recipes_Result> fn_select_Recipes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_Recipes_Result>("[TestDataEntities].[fn_select_Recipes]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_RecipesView")]
        public virtual IQueryable<fn_select_RecipesView_Result> fn_select_RecipesView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesView_Result>("[TestDataEntities].[fn_select_RecipesView]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_CurrentProductView")]
        public virtual IQueryable<fn_select_CurrentProductView_Result> fn_select_CurrentProductView(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentProductView_Result>("[TestDataEntities].[fn_select_CurrentProductView](@ProductCode)", productCodeParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_RecipesBisView")]
        public virtual IQueryable<fn_select_RecipesBisView_Result> fn_select_RecipesBisView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RecipesBisView_Result>("[TestDataEntities].[fn_select_RecipesBisView]()");
        }
    
        public virtual int Pr_DeleteMercuryRecord(string materialCode)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteMercuryRecord", materialCodeParameter);
        }
    
        public virtual int Pr_InsertMercuryRecord(string materialCode, string userName)
        {
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_InsertMercuryRecord", materialCodeParameter, userNameParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_ProductionByCodeAndPeriod")]
        public virtual IQueryable<fn_select_ProductionByCodeAndPeriod_Result> fn_select_ProductionByCodeAndPeriod(string productCode, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ProductionByCodeAndPeriod_Result>("[TestDataEntities].[fn_select_ProductionByCodeAndPeriod](@ProductCode, @dateStart, @dateEnd)", productCodeParameter, dateStartParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<SelectStockBalancesMes_Result> SelectStockBalancesMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesMes_Result>("SelectStockBalancesMes");
        }
    
        public virtual ObjectResult<SelectStockBalancesMes1_Result> SelectStockBalancesMes1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesMes1_Result>("SelectStockBalancesMes1");
        }
    
        [DbFunction("TestDataEntities", "fn_select_LatinStorageNames")]
        public virtual IQueryable<fn_select_LatinStorageNames_Result> fn_select_LatinStorageNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_LatinStorageNames_Result>("[TestDataEntities].[fn_select_LatinStorageNames]()");
        }
    
        public virtual int Insert_WorkPlanTableRecord(Nullable<System.DateTime> datework, string lineName, string prodCode, Nullable<double> quantity)
        {
            var dateworkParameter = datework.HasValue ?
                new ObjectParameter("datework", datework) :
                new ObjectParameter("datework", typeof(System.DateTime));
    
            var lineNameParameter = lineName != null ?
                new ObjectParameter("LineName", lineName) :
                new ObjectParameter("LineName", typeof(string));
    
            var prodCodeParameter = prodCode != null ?
                new ObjectParameter("ProdCode", prodCode) :
                new ObjectParameter("ProdCode", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_WorkPlanTableRecord", dateworkParameter, lineNameParameter, prodCodeParameter, quantityParameter);
        }
    
        public virtual int Modify_WorkPlanTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Modify_WorkPlanTable");
        }
    
        public virtual int Update_WorkPlanTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_WorkPlanTable");
        }
    
        public virtual int Insert_WorkPlanTableRecord1(Nullable<System.DateTime> datework, string lineName, string prodCode, string group, Nullable<double> quantity)
        {
            var dateworkParameter = datework.HasValue ?
                new ObjectParameter("datework", datework) :
                new ObjectParameter("datework", typeof(System.DateTime));
    
            var lineNameParameter = lineName != null ?
                new ObjectParameter("LineName", lineName) :
                new ObjectParameter("LineName", typeof(string));
    
            var prodCodeParameter = prodCode != null ?
                new ObjectParameter("ProdCode", prodCode) :
                new ObjectParameter("ProdCode", typeof(string));
    
            var groupParameter = group != null ?
                new ObjectParameter("Group", group) :
                new ObjectParameter("Group", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_WorkPlanTableRecord1", dateworkParameter, lineNameParameter, prodCodeParameter, groupParameter, quantityParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_SpicesData")]
        public virtual IQueryable<fn_select_SpicesData_Result> fn_select_SpicesData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_SpicesData_Result>("[TestDataEntities].[fn_select_SpicesData]()");
        }
    
        public virtual ObjectResult<SelectStockBalancesPlant2_Result> SelectStockBalancesPlant2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStockBalancesPlant2_Result>("SelectStockBalancesPlant2");
        }
    
        public virtual ObjectResult<pr_GetOPZ_Result> pr_GetOPZ(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetOPZ_Result>("pr_GetOPZ", startParameter, endParameter);
        }
    
        public virtual int Pr_DeleteAppRecord(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_DeleteAppRecord", iDParameter);
        }
    
        [DbFunction("TestDataEntities", "fn_select_CommentData")]
        public virtual IQueryable<fn_select_CommentData_Result> fn_select_CommentData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CommentData_Result>("[TestDataEntities].[fn_select_CommentData]()");
        }
    
        [DbFunction("TestDataEntities", "fn_select_CommentDataID")]
        public virtual IQueryable<fn_select_CommentDataID_Result> fn_select_CommentDataID(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CommentDataID_Result>("[TestDataEntities].[fn_select_CommentDataID](@Code)", codeParameter);
        }
    
        public virtual int pr_InsertCommentData1(Nullable<long> iD, string code, string naim, Nullable<bool> active, string comment, string userName)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var naimParameter = naim != null ?
                new ObjectParameter("Naim", naim) :
                new ObjectParameter("Naim", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertCommentData1", iDParameter, codeParameter, naimParameter, activeParameter, commentParameter, userNameParameter);
        }
    
        public virtual ObjectResult<pr_GetMercuryComponent_Result> pr_GetMercuryComponent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetMercuryComponent_Result>("pr_GetMercuryComponent");
        }
    }
}
