//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EDBEntities : DbContext
    {
        public EDBEntities()
            : base("name=EDBEntities")
        {
            this.Database.CommandTimeout = 600;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tJob> tJob { get; set; }
        public virtual DbSet<tMaterial> tMaterial { get; set; }
        public virtual DbSet<tMaterialCustomProperty> tMaterialCustomProperty { get; set; }
        public virtual DbSet<tMaterialUseActual> tMaterialUseActual { get; set; }
        public virtual DbSet<tProduct> tProduct { get; set; }
    
        [DbFunction("EDBEntities", "fn_select_MaterialUsingByProduct")]
        public virtual IQueryable<fn_select_MaterialUsingByProduct_Result> fn_select_MaterialUsingByProduct(Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd, string materialCode)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_MaterialUsingByProduct_Result>("[EDBEntities].[fn_select_MaterialUsingByProduct](@dateStart, @DateEnd, @MaterialCode)", dateStartParameter, dateEndParameter, materialCodeParameter);
        }
    
        public virtual ObjectResult<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutComment_Result> f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutComment_Result>("f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutComment");
        }
    
        public virtual ObjectResult<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentBis_Result> f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentBis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentBis_Result>("f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentBis");
        }
    
        [DbFunction("EDBEntities", "fn_select_PlanDayli")]
        public virtual IQueryable<fn_select_PlanDayli_Result> fn_select_PlanDayli(Nullable<System.DateTime> dateTime)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_PlanDayli_Result>("[EDBEntities].[fn_select_PlanDayli](@DateTime)", dateTimeParameter);
        }
    
        public virtual ObjectResult<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentMody_Result> f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentMody()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentMody_Result>("f_spMaterialLot_GetAllByWarehouseAndZoneFromNav_IT6WithoutCommentMody");
        }
    
        [DbFunction("EDBEntities", "fn_select_CurrentMaterials")]
        public virtual IQueryable<fn_select_CurrentMaterials_Result> fn_select_CurrentMaterials(Nullable<System.DateTime> dateTime)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_CurrentMaterials_Result>("[EDBEntities].[fn_select_CurrentMaterials](@DateTime)", dateTimeParameter);
        }
    
        [DbFunction("EDBEntities", "fn_select_FactConsurmption")]
        public virtual IQueryable<fn_select_FactConsurmption_Result> fn_select_FactConsurmption()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_FactConsurmption_Result>("[EDBEntities].[fn_select_FactConsurmption]()");
        }
    
        [DbFunction("EDBEntities", "fn_select_ProdNames")]
        public virtual IQueryable<fn_select_ProdNames_Result> fn_select_ProdNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_ProdNames_Result>("[EDBEntities].[fn_select_ProdNames]()");
        }
    
        public virtual ObjectResult<pr_GetAlarmWaste_Result> pr_GetAlarmWaste()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetAlarmWaste_Result>("pr_GetAlarmWaste");
        }
    }
}
