//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EquipPerfEntities : DbContext
    {
        public EquipPerfEntities()
            : base("name=EquipPerfEntities")
        {
            this.Database.CommandTimeout = 600; // seconds
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tLineEfficiencyResult> tLineEfficiencyResult { get; set; }
        public virtual DbSet<tLineEvents> tLineEvents { get; set; }
        public virtual DbSet<tMonitorLineName> tMonitorLineName { get; set; }
        public virtual DbSet<RPSettings> RPSettings { get; set; }
    
        [DbFunction("EquipPerfEntities", "fn_select_RPSettings")]
        public virtual IQueryable<fn_select_RPSettings_Result> fn_select_RPSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_select_RPSettings_Result>("[EquipPerfEntities].[fn_select_RPSettings]()");
        }
    }
}
