//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOPZList
    {
        public int ID { get; set; }
        public string MatCode { get; set; }
        public string MatName { get; set; }
        public Nullable<bool> IsBase { get; set; }
    }
}
