//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPSettings
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductSpeed { get; set; }
        public string ProductGroup { get; set; }
        public string ProductionLine { get; set; }
        public string ProductTrademark { get; set; }
        public string ProductSubGroup { get; set; }
        public Nullable<double> PackCoefficient { get; set; }
        public decimal BatchSize { get; set; }
        public Nullable<int> K { get; set; }
        public string NewFileData { get; set; }
    }
}
