//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBlockedMaterial
    {
        public long id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public bool Using { get; set; }
    }
}
