//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tJob
    {
        public int ID { get; set; }
        public string ExternalID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public int Type { get; set; }
        public string Lot { get; set; }
        public string SubLot { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> PlannedStartDateTime { get; set; }
        public Nullable<int> PlannedDurationSeconds { get; set; }
        public string Capture01 { get; set; }
        public string Capture02 { get; set; }
        public string Capture03 { get; set; }
        public string Capture04 { get; set; }
        public string Capture05 { get; set; }
        public string Capture06 { get; set; }
        public string Capture07 { get; set; }
        public string Capture08 { get; set; }
        public string Capture09 { get; set; }
        public string Capture10 { get; set; }
        public string Capture11 { get; set; }
        public string Capture12 { get; set; }
        public string Capture13 { get; set; }
        public string Capture14 { get; set; }
        public string Capture15 { get; set; }
        public string Capture16 { get; set; }
        public string Capture17 { get; set; }
        public string Capture18 { get; set; }
        public string Capture19 { get; set; }
        public string Capture20 { get; set; }
        public int UserState { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
    }
}
