//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLineEvents
    {
        public int Id { get; set; }
        public string Job { get; set; }
        public int AreaId { get; set; }
        public int Shift { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string PersonStart { get; set; }
        public string PersonEnd { get; set; }
        public bool Status { get; set; }
        public int EventId { get; set; }
    }
}
