//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLineEfficiencyResult
    {
        public int Id { get; set; }
        public int LineEventId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ExternalId { get; set; }
        public string LotForErp { get; set; }
        public string MaterialName { get; set; }
        public string MaterialCode { get; set; }
        public string SystemName { get; set; }
        public int AreaId { get; set; }
        public double Quantity { get; set; }
        public double ProductSpeed { get; set; }
        public string ProductGroup { get; set; }
        public double ProductionDuration { get; set; }
        public double LineEfficiency { get; set; }
        public double PrimaryEfficiency { get; set; }
        public double SecondaryEfiiciency { get; set; }
        public double TimeLost { get; set; }
        public double TimeLossRegistered { get; set; }
        public string PersQuantity { get; set; }
    }
}
