//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMaterialCustomProperty
    {
        public int ID { get; set; }
        public int MaterialID { get; set; }
        public int CustomPropertyID { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
    
        public virtual tMaterial tMaterial { get; set; }
    }
}
