//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMaterialUseActual
    {
        public int ID { get; set; }
        public int JobID { get; set; }
        public int SystemID { get; set; }
        public Nullable<int> BatchStepID { get; set; }
        public int MaterialID { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Quantity { get; set; }
        public string Lot { get; set; }
        public string SubLot { get; set; }
        public string User { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
    }
}
