//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPlannedMeatContainers
    {
        public long id { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string MaterialPostingGroup { get; set; }
        public string LocationCode { get; set; }
        public double Quantity { get; set; }
        public string LotNo { get; set; }
        public string LotDescription { get; set; }
        public string ContainerNo { get; set; }
        public int ExpWeek { get; set; }
        public System.DateTime ExpDT { get; set; }
        public System.DateTime DateWork { get; set; }
        public Nullable<System.DateTime> AlterDate { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
    }
}
