//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantPlanning.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public int ProductSetID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> ConsumedMaterialID { get; set; }
        public Nullable<int> ProducedMaterialID { get; set; }
        public string Attribute01 { get; set; }
        public string Attribute02 { get; set; }
        public string Attribute03 { get; set; }
        public string Attribute04 { get; set; }
        public string Attribute05 { get; set; }
        public string Attribute06 { get; set; }
        public string Attribute07 { get; set; }
        public string Attribute08 { get; set; }
        public string Attribute09 { get; set; }
        public string Attribute10 { get; set; }
        public string Attribute11 { get; set; }
        public string Attribute12 { get; set; }
        public string Attribute13 { get; set; }
        public string Attribute14 { get; set; }
        public string Attribute15 { get; set; }
        public string Attribute16 { get; set; }
        public string Attribute17 { get; set; }
        public string Attribute18 { get; set; }
        public string Attribute19 { get; set; }
        public string Attribute20 { get; set; }
        public Nullable<int> Color { get; set; }
        public int DisplayOrder { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
    }
}
